### ISSUE TITLE
Failed parsing should throw an exception

### ISSUE THREAD

**Issue by matthieumontaigu** [artefactory/artefact.connectors#57]
Sample input: 
`CookieID;InsertionID;NomInsertion;PageID;NomPage;DateLog;Jour;ImageID;NomImage;AnnonceurID;CountryID;countryName;StateID;stateName;Targeting;CityId;cityName;BrowserId;NomBrowser;screenw;screenh;OSId;NomOS;Referrer;UserAgent;linespeed;carrierid;postalcode;Filter;DateLogUTC;LogType`

```
def parse(row):
    from artefact.connectors.smart.clicks.line import Line
    
    try:
        parsed_lines = Line.parse(row.line)
        return parsed_lines
    except Exception as e:
        pass
```

**Comment by d-tw** [comment]
Fixed in 56991e0619e845aaa5e25fe9dc991cbbed130df0
